### ISSUE TITLE
Let's update this interactive with the latest players

### ISSUE THREAD

**Issue by freejoe76** [nydailynews/russia-connex#28]
Would Slattery be the right person?

**Comment by kelliparker** [comment]
The spreadsheet is in the works.
https://docs.google.com/spreadsheets/d/1cRaUbt-rOLaFoYBjkxmohYZioqPLASfpE2BQtG-fNSA/edit#gid=0

**Comment by freejoe76** [comment]
Woo hoo http://interactive.nydailynews.com/project/donald-trump-ties-russia-key-players/
